// Mocks generated by Mockito 5.4.6 from annotations
// in bodymetrics/test/feature/weight_picker/presentation/cubit/weight_picker_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bodymetrics/core/index.dart' as _i2;
import 'package:bodymetrics/domain/index.dart' as _i4;
import 'package:bodymetrics/feature/weight_picker/domain/entity/bmi_value.dart'
    as _i7;
import 'package:bodymetrics/feature/weight_picker/domain/use_case/calculate_bmi_use_case.dart'
    as _i6;
import 'package:bodymetrics/feature/weight_picker/domain/use_case/save_weight_use_case.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserUseCase extends _i1.Mock implements _i2.UserUseCase {
  @override
  _i3.Future<_i2.User?> executeWithParams({_i4.ParamsEntity? params}) =>
      (super.noSuchMethod(
            Invocation.method(#executeWithParams, [], {#params: params}),
            returnValue: _i3.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.User?>.value(),
          )
          as _i3.Future<_i2.User?>);

  @override
  _i3.Future<_i2.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.User?>.value(),
          )
          as _i3.Future<_i2.User?>);

  @override
  _i3.Future<_i2.User?> getCurrentUserWithMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserWithMetrics, []),
            returnValue: _i3.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.User?>.value(),
          )
          as _i3.Future<_i2.User?>);

  @override
  _i3.Future<_i2.User?> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i3.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.User?>.value(),
          )
          as _i3.Future<_i2.User?>);
}

/// A class which mocks [SaveWeightUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWeightUseCase extends _i1.Mock implements _i5.SaveWeightUseCase {
  @override
  _i3.Future<bool> executeWithParams({_i2.UserMetric? params}) =>
      (super.noSuchMethod(
            Invocation.method(#executeWithParams, [], {#params: params}),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [CalculateBmiUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateBmiUseCase extends _i1.Mock
    implements _i6.CalculateBmiUseCase {
  @override
  _i3.Future<double> executeWithParams({_i7.BmiValue? params}) =>
      (super.noSuchMethod(
            Invocation.method(#executeWithParams, [], {#params: params}),
            returnValue: _i3.Future<double>.value(0.0),
            returnValueForMissingStub: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);
}
