// Mocks generated by Mockito 5.4.6 from annotations
// in bodymetrics/test/domain/repository/sync_data_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bodymetrics/core/base/metrics_api_service_base.dart' as _i4;
import 'package:bodymetrics/core/base/user_api_service_base.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserApiServiceBase].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: duplicate_ignore
// ignore: must_be_immutable
class MockUserApiServiceBase extends _i1.Mock
    implements _i2.UserApiServiceBase {
  @override
  _i3.Future<Map<String, dynamic>> createUser(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [data]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> updateUser(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [id, data]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [MetricsApiServiceBase].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: duplicate_ignore
// ignore: must_be_immutable
class MockMetricsApiServiceBase extends _i1.Mock
    implements _i4.MetricsApiServiceBase {
  @override
  _i3.Future<Map<String, dynamic>> createMetric(
    int? userId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMetric, [userId, data]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMetricsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMetricsByUserId, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}
