// Mocks generated by Mockito 5.4.6 from annotations
// in bodymetrics/test/domain/use_case/user_use_case_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bodymetrics/core/index.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i3.Future<_i2.User?> executeWithParams({Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
            Invocation.method(#executeWithParams, [], {#params: params}),
            returnValue: _i3.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.User?>.value(),
          )
          as _i3.Future<_i2.User?>);

  @override
  _i3.Future<_i2.User?> getUserWithMetrics({Map<String, dynamic>? filters}) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWithMetrics, [], {#filters: filters}),
            returnValue: _i3.Future<_i2.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i2.User?>.value(),
          )
          as _i3.Future<_i2.User?>);

  @override
  _i3.Future<int?> saveUser({Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [], {#data: data}),
            returnValue: _i3.Future<int?>.value(),
            returnValueForMissingStub: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<int?> updateUser({Map<String, dynamic>? data}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {#data: data}),
            returnValue: _i3.Future<int?>.value(),
            returnValueForMissingStub: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);
}
